export const stateCity = [
  {
    name: 'Australian Capital Territory',
    code: 'ACT',
    city: ['Canberra'],
  },
  {
    name: 'New South Wales',
    code: 'NSW',
    city: [
      'Sydney',
      'Central Coast',
      'Wollongong',
      'Newcastle',
      'Wagga Wagga',
      'Port Macquarie',
      'Bathurst',
      'Quakers Hill',
      'Armidale',
      'Griffith',
      'Taree',
      'Banora Point',
      'Cessnock',
      'Forster',
      'Penrith',
      'Goonellabah',
      'Campbelltown',
      'Rutherford',
      'Muswellbrook',
      'Grafton',
      'Bowral',
      'Casino',
      'Parkes',
      'Mudgee',
      'Inverell',
      'Nowra',
      'Flemington',
      'Ballina',
      'Moss Vale',
      'Springwood',
      'Cowra',
      'Tweed Heads',
      'Emu Plains',
      'Katoomba',
      'Young',
      'Kingscliff',
      'Leeton',
      'Blaxland',
      'Sanctuary Point',
      'Moama',
      'Merrimac',
      'Moree',
      'Murwillumbah',
      'Bomaderry',
      'Helensburgh',
      'Deniliquin',
      'Lennox Head',
      'Nambucca Heads',
      'Wauchope',
      'Tumut',
      'Tuncurry',
      'Yamba',
      'Kurri Kurri',
      'Yass',
      'Mittagong',
      'Cootamundra',
      'Narrabri',
      'Corowa',
      'Richmond',
      'Woolgoolga',
      'Glen Innes',
      'Alstonville',
      'Worragee',
      'Glenbrook',
      'Tahmoor',
      'Scone',
      'Kiama Downs',
      'Hazelbrook',
      'Lithgow',
      'Salamander Bay',
      'Albury',
      'Wingham',
      'Old Bar',
      'Wyong',
      'Wellington',
      'Thirlmere',
      'Temora',
      'The Entrance',
      'Gerringong',
      'Picton',
      'Narrandera',
      'Suffolk Park',
      'Weston',
      'Sawtell',
      'Silverdale',
      'Bay View',
      'Lismore',
      'Merimbula',
      'Lake Cathie',
      'Cobar',
      'Bellingen',
      'Mullumbimby',
      'Tura Beach',
      'Eden',
      'Bogangar',
      'Shoalhaven Heads',
      'Blayney',
      'Wilton',
      'Terranora',
      'Saint Georges Basin',
      'Culburra',
      'Tea Gardens',
      'Bonny Hills',
      'Urunga',
      'Vincentia',
      'West Wyalong',
      'Howlong',
      'Lawson',
      'Narooma',
      'Quirindi',
      'Condobolin',
      'Aberdare',
      'Gilgandra',
      'Sandy Beach',
      'Hill Top',
      'Jindabyne',
      'The Oaks',
      'Heddon Greta',
      'Grenfell',
      'Bangalow',
      'Manilla',
      'Camden Haven',
      'Wallerawang',
      'Mulwala',
      'Windsor',
      'Batehaven',
      'Brunswick Heads',
      'Denman',
      'Bourke',
      'Tathra',
      'Canowindra',
      'Walgett',
      'Surfside',
      'Greenwell Point',
      'Valley Heights',
      'Oakdale',
      'Mollymook',
    ],
  },
  {
    name: 'Northern Territory',
    code: 'NT',
    city: ['Darwin', 'Palmerston'],
  },
  {
    name: 'Queensland',
    code: 'QLD',
    city: [
      'Brisbane',
      'Gold Coast',
      'Ipswich',
      'Townsville',
      'Cairns',
      'Toowoomba',
      'Mackay',
      'Hervey Bay',
      'Buderim',
      'Caloundra',
      'Gladstone',
      'Southport',
      'Maroochydore',
      'Ormeau',
      'Nambour',
      'Corinda',
      'Kingaroy',
      'Andergrove',
      'Bargara',
      'Mareeba',
      'Beenleigh',
      'Charters Towers',
      'Urraween',
      'Bongaree',
      'Burpengary',
      'Waterford',
      'North Mackay',
      'Cannonvale',
      'Point Vernon',
      'Palmwoods',
      'Bucasia',
      'Glenella',
      'Rasmussen',
      'Deeragun',
      'Peregian Beach',
      'Scarness',
      'Proserpine',
      'Beachmere',
      'Thursday Island',
      'Freshwater',
      'Kawana Waters',
      'Yaroomba',
      'Innisfail',
    ],
  },
  {
    name: 'South Australia',
    code: 'SA',
    city: [
      'Adelaide',
      'Mount Gambier',
      'Whyalla',
      'Murray Bridge',
      'Mount Barker',
      'Port Augusta',
      'Strathalbyn',
      'Nuriootpa',
      'Nairne',
      'Encounter Bay',
      'Millicent',
      'Renmark',
      'Tanunda',
      'Victor Harbor',
      'Berri',
      'Loxton',
      'Roxby Downs',
      'Aldgate',
      'McLaren Vale',
      'Stirling',
      'Kapunda',
      'Goolwa',
      'Hahndorf',
      'Willunga',
      'Williamstown',
      'Freeling',
      'Lobethal',
      'Barmera',
      'Woodside',
      'Lyndoch',
      'Waikerie',
    ],
  },
  {
    name: 'Tasmania',
    code: 'TAS',
    city: [
      'Hobart',
      'Launceston',
      'Burnie',
      'Kingston',
      'Ulverstone',
      'New Norfolk',
      'Wynyard',
      'George Town',
      'Latrobe',
      'Legana',
      'Somerset',
      'Longford',
      'Perth',
      'Penguin',
      'Smithton',
      'Deloraine',
      'Margate',
      'Dodges Ferry',
      'Hadspen',
      'Queenstown',
      'Westbury',
      'Seven Mile Beach',
      'Evandale',
    ],
  },
  {
    name: 'Victoria',
    code: 'VIC',
    city: [
      'Cranbourne',
      'Geelong',
      'Ballarat',
      'Bendigo',
      'Pakenham',
      'Frankston',
      'Sunbury',
      'Dandenong',
      'Warrnambool',
      'Traralgon',
      'Mount Eliza',
      'Lara',
      'Horsham',
      'Wallan',
      'Barwon Heads',
      'Morwell',
      'Leopold',
      'Swan Hill',
      'Mount Evelyn',
      'Colac',
      'Rye',
      'Mooroopna',
      'Maryborough',
      'Narre Warren North',
      'Clifton Springs',
      'Castlemaine',
      'Kyabram',
      'Dromana',
      'Seymour',
      'Lakes Entrance',
      'Leongatha',
      'Stawell',
      'Whittlesea',
      'Inverloch',
      'Churchill',
      'Maffra',
      'Broadford',
      'Drysdale',
      'Tatura',
      'Cockatoo',
      'Mansfield',
      'Korumburra',
      'Trafalgar',
      'Pearcedale',
      'Numurkah',
      'Buninyong',
      'Kerang',
      'Paynesville',
      'Maddingley',
      'Port Fairy',
      'Koo-Wee-Rup',
      'Euroa',
      'Red Cliffs',
      'Woori Yallock',
      'Camperdown',
      'McCrae',
      'North Wonthaggi',
      'Launching Place',
      'Rutherglen',
      'Beaconsfield Upper',
      'Baxter',
      'Saint Arnaud',
      'Orbost',
      'Wattleglen',
      'Yarram',
      'Curlewis',
      'Nathalia',
      'Cobden',
      'Yarragon',
      'San Remo',
      'Yallourn North',
      'Wahgunyah',
    ],
  },
  {
    name: 'Western Australia',
    code: 'WA',
    city: ['Perth', 'Mandurah', 'Australind', 'Fremantle', 'Boulder', 'Esperance', 'Drummond Cove'],
  },
]
