export const dummyData = {
  totalItems: 4,
  items: [
    {
      id: 1,
      cert_number: '109583065',
      psaLink: 'https://www.psacard.com/cert/109583065',
      cardName: 'Charizard EX',
      grade: 'GEM MT 10',
      PSACert: {
        CertNumber: '109583665',
        SpecID: 9603030,
        SpecNumber: 'DTK6000200',
        LabelType: 'LighthouseLabel',
        ReverseBarCode: true,
        Year: '2023',
        Brand: 'POKEMON MEW EN-151',
        Category: 'TCG Cards',
        CardNumber: '199',
        Subject: 'CHARIZARD ex',
        Variety: 'SPECIAL ILLUSTRATION RARE',
        IsPSADNA: false,
        IsDualCert: false,
        GradeDescription: 'GEM MT 10',
        CardGrade: 'GEM MT 10',
        TotalPopulation: 18436,
        TotalPopulationWithQualifier: 0,
        PopulationHigher: 0,
      },
      image_link: [
        {
          IsFrontImage: false,
          ImageURL: 'https://d1htnxwo4o0jhw.cloudfront.net/cert/176327334/wQSmZ1yD8UOD6KdBX1P8aQ.jpg',
        },
        {
          IsFrontImage: true,
          ImageURL: 'https://d1htnxwo4o0jhw.cloudfront.net/cert/176327334/Y2bNWJHvi0SiBGfyda9Jsg_e337b.jpg',
        },
      ],
    },
    {
      id: 2,
      cert_number: '109583066',
      psaLink: 'https://www.psacard.com/cert/109583066',
      cardName: 'Pikachu VMAX',
      grade: 'MINT 9',
      PSACert: {
        CertNumber: '109583665',
        SpecID: 9603030,
        SpecNumber: 'DTK6000200',
        LabelType: 'LighthouseLabel',
        ReverseBarCode: true,
        Year: '2023',
        Brand: 'POKEMON MEW EN-151',
        Category: 'TCG Cards',
        CardNumber: '199',
        Subject: 'CHARIZARD ex',
        Variety: 'SPECIAL ILLUSTRATION RARE',
        IsPSADNA: false,
        IsDualCert: false,
        GradeDescription: 'GEM MT 10',
        CardGrade: 'GEM MT 10',
        TotalPopulation: 18436,
        TotalPopulationWithQualifier: 0,
        PopulationHigher: 0,
      },
      image_link: [
        {
          IsFrontImage: false,
          ImageURL: 'https://d1htnxwo4o0jhw.cloudfront.net/cert/176327334/wQSmZ1yD8UOD6KdBX1P8aQ.jpg',
        },
        {
          IsFrontImage: true,
          ImageURL: 'https://d1htnxwo4o0jhw.cloudfront.net/cert/176327334/Y2bNWJHvi0SiBGfyda9Jsg_e337b.jpg',
        },
      ],
    },
    {
      id: 3,
      cert_number: '109583067',
      psaLink: 'https://www.psacard.com/cert/109583067',
      cardName: 'Blastoise GX',
      grade: 'GEM MT 10',
      PSACert: {
        CertNumber: '109583665',
        SpecID: 9603030,
        SpecNumber: 'DTK6000200',
        LabelType: 'LighthouseLabel',
        ReverseBarCode: true,
        Year: '2023',
        Brand: 'POKEMON MEW EN-151',
        Category: 'TCG Cards',
        CardNumber: '199',
        Subject: 'CHARIZARD ex',
        Variety: 'SPECIAL ILLUSTRATION RARE',
        IsPSADNA: false,
        IsDualCert: false,
        GradeDescription: 'GEM MT 10',
        CardGrade: 'GEM MT 10',
        TotalPopulation: 18436,
        TotalPopulationWithQualifier: 0,
        PopulationHigher: 0,
      },
      image_link: [
        {
          IsFrontImage: false,
          ImageURL: 'https://d1htnxwo4o0jhw.cloudfront.net/cert/176327334/wQSmZ1yD8UOD6KdBX1P8aQ.jpg',
        },
        {
          IsFrontImage: true,
          ImageURL: 'https://d1htnxwo4o0jhw.cloudfront.net/cert/176327334/Y2bNWJHvi0SiBGfyda9Jsg_e337b.jpg',
        },
      ],
    },
    {
      id: 4,
      cert_number: '109583068',
      psaLink: 'https://www.psacard.com/cert/109583068',
      cardName: 'Venusaur V',
      grade: 'NM-MT 8',
      PSACert: {
        CertNumber: '109583665',
        SpecID: 9603030,
        SpecNumber: 'DTK6000200',
        LabelType: 'LighthouseLabel',
        ReverseBarCode: true,
        Year: '2023',
        Brand: 'POKEMON MEW EN-151',
        Category: 'TCG Cards',
        CardNumber: '199',
        Subject: 'CHARIZARD ex',
        Variety: 'SPECIAL ILLUSTRATION RARE',
        IsPSADNA: false,
        IsDualCert: false,
        GradeDescription: 'GEM MT 10',
        CardGrade: 'GEM MT 10',
        TotalPopulation: 18436,
        TotalPopulationWithQualifier: 0,
        PopulationHigher: 0,
      },
      image_link: [
        {
          IsFrontImage: false,
          ImageURL: 'https://d1htnxwo4o0jhw.cloudfront.net/cert/176327334/wQSmZ1yD8UOD6KdBX1P8aQ.jpg',
        },
        {
          IsFrontImage: true,
          ImageURL: 'https://d1htnxwo4o0jhw.cloudfront.net/cert/176327334/Y2bNWJHvi0SiBGfyda9Jsg_e337b.jpg',
        },
      ],
    },
  ],
}
